version: '3'
dotenv:
  - ".env"
tasks:
  build:dev:
    desc: Build dev enviroment
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
      - docker container cp bin/apache/default.conf budgetcontrol-ms-notification:/etc/apache2/sites-available/budgetcontrol.cloud.conf
      - docker container exec budgetcontrol-ms-notification service apache2 restart
  run:db:
    desc: Run database
    cmds:
      - docker-compose -f docker-compose.db.yml up -d database
  run:cache:
    desc: Run database
    cmds:
      - docker-compose -f docker-compose.db.yml up -d database